import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { AutoGeneratedPageRoutingModule } from './auto-generated-routing.module';

import { AutoGeneratedPage } from './auto-generated.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    AutoGeneratedPageRoutingModule
  ],
  declarations: [AutoGeneratedPage]
})
export class AutoGeneratedPageModule {}
